Update leaf.py
PyTables/PyTables pull request #1010
Opened 2023-03-21 04:38 UTC by wony-zheng

avoid RuntimeWarning: overflow encountered in long_scalars

2023-03-21 06:30 UTC, avalentino commented on tables/leaf.py
> +        expected_mb = np.int32((np.int64(expectedrows) * rowsize) // MB)
Sorry, I have not analysed the problem in depth but the need of a double casting looks very strange to me.
What is the data type of `expectedrows` normally?
In any case Python `int` should never be subject to overflow. Is it not enough ro have a single cast to `int`?

2023-05-20 09:30 UTC, avalentino requested changes

2023-05-20 09:30 UTC, avalentino commented on tables/leaf.py
> +        expected_mb = np.int32((np.int64(expectedrows) * rowsize) // MB)
@wony-zheng could you please confirm that the following path works for you?

```patch
-        expected_mb = (expectedrows * rowsize) // MB
+        expected_mb = (int(expectedrows) * rowsize) // MB)
```

2024-08-12 08:57 UTC, ivilata commented
This should be fixed in a more generic way (by sanitizing `expectedrows` user input) by commit 7d08ab1. Thanks anyway @wony-zheng by the report!

2024-08-12 08:57 UTC, closed without merging